### PR TITLE
fix implicitly returning functions from functions

### LINKED ISSUE #2: Inner functions are not implicitly returned
Currently, this:

```js
fn () ->
  value = 42

  inner () ->
    value
```

results in this:

```js
function fn() {
  const value = 42;

  function inner() {
    return value;
  }
}
```

but it `inner` should be implicitly returned like so:

```js
function fn() {
  const value = 42;

  function inner() {
    return value;
  }

  return inner;
}
```

### PR DESCRIPTION
**Pull request by haltcase**
Closes #2 

Also includes a small fix for running tests on Windows, replacing `node node_modules/.bin/mocha test` with the simpler `mocha test` which is cross platform.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -281,17 +281,44 @@ export default function (babel) {
     return (typeof node.skinny === "boolean");
   }
 
+  function getCompletionRecords(path) {
```
Comment (rattrayalex) [inline src/index.js]: let's add a comment indicating where this is copied from: 

```
c/p babel-traverse/src/path/family.js getCompletionRecords
function getCompletionRecords(path) {
```

Comment (rattrayalex) [reply src/index.js]: might also want to rename the function to prevent confusion...

**Comment by wcjohnson** [comment]
Can I propose renaming `getCompletionRecords` to something like `getTailExpressions`? This would clarify and avoid confusion with the Babel algorithm, which is different.

**Comment by haltcase** [comment]
@wcjohnson I think that's a good move. @rattrayalex ?

File: src/index.js [hunk 2]
```diff
@@ -281,17 +281,44 @@ export default function (babel) {
...
+    let paths = [];
+
+    const add = function add(_path) {
+      if (_path) paths = paths.concat(getCompletionRecords(_path));
+    };
+
+    if (path.isIfStatement()) {
+      add(path.get("consequent"));
+      add(path.get("alternate"));
+    } else if (path.isDoExpression() || path.isFor() || path.isWhile()) {
```
Comment (rattrayalex) [inline src/index.js]: if we add a `allowLoops` param to `getCompletionRecords`, we can change this section to...

```js
} else if (path.isDoExpression()) {
  add(path.get("body"));
} else if (allowLoops && (path.isFor() || path.isWhile())) {
  add(path.get("body"));
}
```
and then completely clean up `const loop = targetPath.findParent((p) => p.isLoop() && p.getFunctionParent() === path);`, below

Comment (rattrayalex) [reply src/index.js]: (we'll want to pass call it with allowLoop `false` for implicitReturns and `true` for comprehensions

**Review by rattrayalex — COMMENTED** [review]
looking good so far!

**Comment by rattrayalex** [comment]
Yeah I like `getTailExpressions`

**Comment by rattrayalex** [comment]
@citycide let's also start using this for comprehensions in this PR?

**Comment by wcjohnson** [comment]
@rattrayalex @citycide 

Alternatively, I am already working on AST transforms for object comprehensions, so if you want to merge this sooner rather than later, I am willing to make the required changes for comprehensions on my end.

**Comment by haltcase** [comment]
@rattrayalex @wcjohnson I made the noted adjustments and then also updated `Function` to use an exit call. Should be a start toward the comprehensions.

File: src/index.js [hunk 3]
```diff
@@ -287,17 +287,47 @@ export default function (babel) {
...
+    const add = function add(_path) {
+      if (_path) paths = paths.concat(getTailExpressions(_path));
+    };
+
+    if (path.isIfStatement()) {
+      add(path.get("consequent"));
+      add(path.get("alternate"));
+    } else if (path.isDoExpression()) {
+      add(path.get("body"));
+    } else if (allowLoops && (path.isFor() || path.isWhile())) {
```
Comment (wcjohnson) [inline src/index.js:303]: cc @rattrayalex 

I am not sure this implementation of the `allowLoops` flag is correct. If you pass `true`, you will get all the tail expressions in the loop (which is probably what you want) however if you pass `false` you will be treating every loop as if it were a tail expression, which is almost definitely bad because loops aren't expressions.

I think there should be an early return here if it is a loop, so that you don't push the loop to the final array.

Comment (wcjohnson) [reply src/index.js:303]: This will also eliminate any need to check for loops in the `addImplicitReturns`, I think.

Comment (rattrayalex) [reply src/index.js:303]: Nope; since a loop is a statement, it's not processed in `addImplicitReturns`; only `ExpressionStatement`s, `VariableDeclaration`s, and `FunctionDeclaration`s are.

File: src/index.js [hunk 4]
```diff
@@ -287,17 +287,47 @@ export default function (babel) {
...
+      add(path.get("body"));
+    } else if (path.isProgram() || path.isBlockStatement()) {
+      add(path.get("body").pop());
+    // } else if (path.isFunction()) {
+      // return getTailExpressions(path.get("body"));
```
Comment (rattrayalex) [inline src/index.js]: we can clean up this comment

File: src/index.js [hunk 5]
```diff
@@ -287,17 +287,47 @@ export default function (babel) {
...
     path.resync();
 
-    const completionRecords = path.get("body").getCompletionRecords();
+    const completionRecords = getTailExpressions(path.get("body"));
     for (const targetPath of completionRecords) {
       // don't implicitly return contents of loops
       // TODO: add linting to discourage
       const loop = targetPath.findParent((p) => p.isLoop() && p.getFunctionParent() === path);
-      if (loop) continue;
+      if (loop || !targetPath.node) continue;
```
Comment (rattrayalex) [inline src/index.js]: as noted elsewhere, I think, `loop` can be removed now.

File: src/index.js (hunk 3 above)
Comment (wcjohnson) [reply src/index.js:303]: Ignore my comments here, algorithm is correct as written.

File: src/index.js [hunk 6]
```diff
@@ -287,17 +287,47 @@ export default function (babel) {
     return (typeof node.skinny === "boolean");
   }
 
+  // c/p babel-traverse/src/path/family.js getCompletionRecords
+  function getTailExpressions(path, allowLoops) {
+    let paths = [];
+
+    const add = function add(_path) {
+      if (_path) paths = paths.concat(getTailExpressions(_path));
```
Comment (wcjohnson) [inline src/index.js]: In order to work right with comprehensions, this needs to read:

```javascript
if (_path) paths = paths.concat(getTailExpressions(_path, allowLoops));
```

File: src/index.js [hunk 7]
```diff
@@ -310,6 +340,8 @@ export default function (babel) {
         // TODO: handle declarations.length > 1
         // TODO: add linting to discourage
         targetPath.insertAfter(t.returnStatement(targetPath.node.declarations[0].id));
+      } else if (targetPath.isFunctionDeclaration()) {
```
Comment (wcjohnson) [inline src/index.js:338]: You might need something here to deal with `NamedArrowDeclaration`s. I did in my comprehension code.

File: src/index.js [hunk 8]
```diff
@@ -985,18 +1017,20 @@ export default function (babel) {
         }
       },
 
-      Function(path) {
-        if (path.node.kind === "constructor" || path.node.kind === "set") return;
+      Function: {
+        exit(path) {
```
Comment (wcjohnson) [inline src/index.js:1020]: I am not actually 100% sure it is necessary to make this an `exit` visitor. Can anyone think of a test case that would exercise this?

Comment (wcjohnson) [reply src/index.js:1020]: Hmm, because it is an exit visitor is maybe why you are getting `NamedArrowDeclaration`s for free...

Comment (haltcase) [reply src/index.js:1020]: Yep we don't need to handle it in implicit returns if we do the `exit` here.

File: package.json [hunk 9]
```diff
@@ -4,7 +4,7 @@
   "description": "Compile LightScript to JavaScript.",
   "main": "index.js",
   "scripts": {
-    "test": "node node_modules/.bin/mocha test",
+    "test": "mocha test",
```
Comment (rattrayalex) [inline package.json:7]: can we make a note in the README that contributors will need to add `node_modules/.bin/` to their PATH?

File: src/index.js (hunk 7 above)
Comment (rattrayalex) [reply src/index.js:338]: (hopefully) not with the `exit` fix; they will have been transformed to `FunctionDeclarations` by this time.

Comment (rattrayalex) [reply src/index.js:338]: (ah, I see this was discussed elsewhere, sorry)

File: package.json (hunk 9 above)
Comment (haltcase) [reply package.json:7]: Shouldn't have to. NPM localizes these. Pretty sure that's cross-platform?

Comment (wcjohnson) [reply package.json:7]: When you run a command through `npm run` (or anywhere inside an npm script) it automatically adds that to the path.

Comment (haltcase) [reply package.json:7]: Yeah, see the [docs on `npm run`](https://docs.npmjs.com/cli/run-script), specifically:

> In addition to the shell's pre-existing `PATH`, `npm run` adds `node_modules/.bin` to the `PATH` provided to scripts. Any binaries provided by locally-installed dependencies can be used without the `node_modules/.bin` prefix.

**Comment by wcjohnson** [comment]
LGTM

File: package.json (hunk 9 above)
Comment (rattrayalex) [reply package.json:7]: oh wow, that's awesome! Didn't know that.

**Review by rattrayalex — APPROVED** [review]
Looks great, thanks @citycide !
